HW by Galieva Railina
AufarZakiev/CPP-2020-2021-HW12 pull request #1
Opened 2021-04-12 12:12 UTC by RaiRG

Насколько оправдано использование наследования в данном задании? Есть ощущение, что было бы проще обойтись классами Country и Transport, добавив лишь поля, которые бы хранили в себе enum class-ы с названиями стран и вида транспорта соответственно))

2021-04-12 12:15 UTC, RaiRG commented
![Снимок экрана 2021-04-12 151417](https://user-images.githubusercontent.com/64270610/114392684-ca3d7f80-9ba1-11eb-9cae-f5050613c189.png)

2021-04-13 17:30 UTC, AufarZakiev requested changes

2021-04-13 17:30 UTC, AufarZakiev commented on mainwindow.cpp
> +  if (fromCountry == "Asia")
Здесь надо сделать покрасивее) без if-else

2021-04-13 17:32 UTC, AufarZakiev commented
Предполагалось, что будет класс Delivery, у которого будут наследники GroundDelivery, SeaDelivery и т.п.
И так действительно получается проще) 
Ведь каждый отвечает за доставку, но хранит в себе свой коэффициент цены.

2021-04-16 09:38 UTC, RaiRG commented
Снова не понимаю работу конструкторов :( Если в файле delivery.cpp, в строке 4 с сигнатурой Delivery(int transport, int country) убрать из списка инициализации Delivery(), программа выкинет ошибку, потому что в строке с koefficients[0] идет обращение к несуществующему блоку памяти... koefficients - вектор, унаследованный от PaymentAPI
Почему так происходит?
Разве порядок выполнения конструкторов не следующий: PaymentAPI() ->Delivery()->Delivery(int transport, int country) ??
То есть по сути, что со списком инициализации, что без, koefficients должен быть уже проинициализирован, т.к. уже заходил в Delivery().

2021-04-16 17:50 UTC, AufarZakiev approved these changes

2021-04-16 17:50 UTC, AufarZakiev commented
Молодец, что разобралась :)

2023-08-24 06:42 UTC, closed without merging